# urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from .views import user_logout, item_list

app_name = 'product_tracking'
urlpatterns = [
    path('', views.custom_login, name='login_view'),
    path('index/', views.index_view, name='index'),
    path('login/', views.custom_login, name='login_view'),
    path('logout/', user_logout, name='logout'),
    path('production_order/', views.production_order, name='production_order'),
    path('label_printing/', views.label_printing, name='label_printing'),
    path('label_reprinting/', views.label_reprinting, name='label_reprinting'),
    path('stock_verification/', views.stock_verification, name='stock_verification'),
    path('stock_approval/', views.stock_approval, name='stock_approval'),
    path('add_user/', views.add_user, name='add_user'),
    path('add_item/', views.add_item, name='add_item'),
    path('add_production_line/', views.add_production_line, name='add_production_line'),
    path('get_production_line/', views.get_production_line, name='get_production_line'),
    path('delete_production_line/', views.delete_production_line, name='delete_production_line'),
    path('user_list/', views.user_list, name='user_list'),
    path('item_list/', item_list, name='item_list'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('update_item/<int:item_id>/', views.update_item, name='update_item'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('get_item_code/', views.get_item_code, name='get_item_code'),
    path('get_line_numbers/', views.get_line_numbers, name='get_line_numbers'),
    path('create_production_order/', views.create_production_order, name='create_production_order'),
    path('get_item_name/<int:item_id>/', views.get_item_name, name='get_item_name'),
    path('get_production_order_list/', views.get_production_order_list, name='get_production_order_list'),
    path('update_production_order/', views.update_production_order, name='update_production_order'),
    path('add_tolerance/', views.add_tolerance, name='add_tolerance'),
    path('get_tolerance_list/', views.get_tolerance_list, name='get_tolerance_list'),
    path('update_tolerance/', views.update_tolerance, name='update_tolerance'),
    path('add_mould/', views.add_mould, name='add_mould'),
    path('get_mould_list/', views.get_mould_list, name='get_mould_list'),
    path('update_mould/', views.update_mould, name='update_mould'),
    path('get_production_order_numbers_by_line/', views.get_production_order_numbers_by_line, name='get_production_order_numbers_by_line'),
    path('get_product_details_by_order/<str:production_order_no>/', views.get_product_details_by_order, name='get_product_details_by_order'),
    path('generate_prn/', views.generate_prn, name='generate_prn'),
    path('get_weight/', views.get_weight, name='get_weight'),
    path('get_batch_data/', views.get_batch_data, name='get_batch_data'),
    path('reprint_label/', views.reprint_label, name='reprint_label'),
    path('add_printer/', views.add_printer, name='add_printer'),
    path('get_printer_list/', views.get_printer_list, name='get_printer_list'),
    path('get_production_lines/', views.get_production_lines, name='get_production_lines'),
    path('update_printer/', views.update_printer, name='update_printer'),
    path('delete_printer/', views.delete_printer, name='delete_printer'),
    path('quality_control/', views.quality_control, name='quality_control'),
    path('approve_qc/', views.approve_qc, name='approve_qc'),
    path('reject_qc/', views.reject_qc, name='reject_qc'),
    path('get_batch_data_for_qc/', views.get_batch_data_for_qc, name='get_batch_data_for_qc'),
    path('generate_carton/', views.generate_carton, name='generate_carton'),
    path('get_single_carton_list/', views.get_single_carton_list, name='get_single_carton_list'),
    path('check_polybag_status/', views.check_polybag_status, name='check_polybag_status'),
    path('short_closure/', views.short_closure, name='short_closure'),
    path('get_production_order_numbers/', views.get_production_order_numbers, name='get_production_order_numbers'),
    path('get_po_details_for_sc/', views.get_po_details_for_sc, name='get_po_details_for_sc'),
    path('save_remark/', views.save_remark, name='save_remark'),
]
